- main.py
- src/loggingColoredFormatter.py
- src/searches.py
Pulling the fixes from udu3324's branch
> usu3324 fixes

- main.py
- src/utils.py
Added the goal into the log and the notifier to see at the end of a run how far away the goal is.
I want to see how much of the goal I reached
Tested with and without goal set. 
Affects nothing else only addition no change of existing code.
The goal line is only added if a goal is set.
> Goal in log and notifier

- src/login.py
Added check if the email has been entered and is in the field before clicking on next button.
> fix: bug when inserting email

- src/searches.py
Added feature of typing letter by letter instead of directly pasting the word and searching.
> char-by-char input feature

- src/login.py
Reverts klept0/MS-Rewards-Farmer#76
> Revert "fix: bug when inserting email"

- main.py
Hello,
Sometimes I get proxie connection errors because they're unreliable, so I've added a reconnection system with 3 attempts if an error occurs.
> Update main.py for retry connection if error

- main.py
- requirements.txt
Pandas is an unused dependency and should be removed.
> remove pandas

- src/login.py
Detects when the 'Protect your account' is triggered and needs to be done manually via an email code.
> Add detection for the 'Protect your account' login blockage

- src/login.py
- src/utils.py
My first attempt at a quick update, feel free to ignore if this is unhelpful or problematic.  I have already protected my account with an additional email address so this is difficult to test.  I'm working on getting more familiar with github nuance as well as Python selenium driver nuance.
> Added a hasty "Let's protect your account" check

- .gitignore
- README.md
I also saw a typo in the Readme
> Add config.yaml to gitignore

- main.py
Moved ReadToEarn to mobile section and use the mobile browser. It belongs there.
> Move Read To Earn To Mobile Section

- .github/ISSUE_TEMPLATE/bug_report.yml
> Attempt fix bug_report.yml

- src/searches.py
> Fix when get google trends fails

- CHANGELOG.md
- MS_reward.bat
- README.md
- generate_task_xml.py
This Pull Request implements the automatic generation of Windows Task Scheduler XML files using a Python script. The script allows users to choose between Miniconda and Anaconda, specify the environment name, and sets the output path to the current working directory. Additionally, a batch file is included to facilitate the execution of the Python script.
- **Python Script**: 
- A new Python script that generates a Task Scheduler XML file.
- The script prompts the user to select between Miniconda and Anaconda.
- The script prompts the user to input the name of the environment they are using.
- The script sets the output path to the current working directory.
- **Batch File**: 
- Added a new batch file (`MS_reward.bat`) that automatically sets the current directory and executes the Python …
> Completed automatic generation of Windows Task Scheduler XML

- src/morePromotions.py
Couple more promos, not sure if the timezone one works if you put in just your own timezone as I didn't test that when I had it
> Add more promos

- src/login.py
Lock/Bann checked after Login.
i smoked a good J
> Pulled Pork - Bann & Lock check

- .github/workflows/build_push_docker_image.yml
- Dockerfile
- docker.sh
- src/browser.py
- src/login.py
Moved the (still WIP) Docker Implementation PR from @charlesbel's repo.
Old discussion can be found [here](https://github.com/charlesbel/Microsoft-Rewards-Farmer/pull/431).
Currently it supports two environmental variables:
- `RUN_ONCE`: if set to `true`, runs the script once and then quits
- `CRON_SCHEDULE`: you can supply a valid cron schedule, or by default it will just run daily at 4 AM.
Builds can be auto-triggered (GitHub Actions) by setting a tag to the commits.
TODO:
> Docker implementation

- src/userAgentGenerator.py
Change userAgentGenerator.py to use lowercase keys in getEdgeVersions
Fixes  #232
> Fix Edge API

- .gitignore
- activities.py
- config.yaml
- src/browser.py
- src/userAgentGenerator.py
- src/utils.py
1. keyError in getEdgeVersions
Looks like users "randomly" get response json with capitalized or uncapitalized key. 
Thus, add temp function to ignore the capitalization.
3. Key Error in `getLanguageCountry()` country in config.yaml is using key 'geolocation', while it's fetched by the wrong key 'location'
```yaml
default:
geolocation: US # Replace with your country code https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2
```
```python
@staticmethod
def getLanguageCountry(language: str, country: str) -> tuple[str, str]:
if not country:
country = CONFIG.get("default").get("location")
```
> fix: resolve KeyError in getEdgeVersions and bug in getLanguageCountry

- main.py
Allows to enhance CLI & scripting experience with this project.
For example, can be used for re-launch the program automatically if it failed.
> Exit 1 on error

- src/userAgentGenerator.py
- src/utils.py
- Apprise notifications disable reverted
- `get_value_ignore_case` renamed to `getValueIgnoreCase` to preserve consistency
See [#237 review comment 1](https://github.com/klept0/MS-Rewards-Farmer/pull/237#discussion_r1875160328) and [#237 review comment 2](https://github.com/klept0/MS-Rewards-Farmer/pull/237#discussion_r1875162199)
> Fix unwanted changes on #237

- .gitignore
- MS_reward.bat
Reverts klept0/MS-Rewards-Farmer#260
> Revert "Automatic VEnv Selection"

- src/searches.py
Updated the Google Trends API integration by switching to the version used in the Netsky Bot
> Google Trends API Update

- src/activities.py
Update following #272 because I merged too fast and forgot to double-check everything.
> refactor: incompleteActivities

- main.py
- src/activities.py
- src/login.py
- src/searches.py
- src/utils.py
- test/test_main.py
- test/test_utils.py
- remove `sendNotification` in favor of `Apprise.notify` directly
- remove apprise notify assertion
- remove stacktrace from apprise notifications
- exit 1 on account error
This PR follows the reflection in https://github.com/klept0/MS-Rewards-Farmer/issues/186#issuecomment-2625680832
Fix #186
> refactor: remove `sendNotification`

- test/test_main.py
> fix test_main

- .pylintrc
- main.py
- src/activities.py
- src/browser.py
- src/loggingColoredFormatter.py
- src/login.py
- src/punchCards.py
- src/readToEarn.py
- src/remainingSearches.py
- src/searches.py
- src/userAgentGenerator.py
- src/utils.py
- Fixed some code style errors
- Disabled the following rules: broad-exception-caught, attribute-defined-outside-init, logging-fstring-interpolation, logging-not-lazy, too-many-branches, too-many-instance-attributes, too-many-statements, too-few-public-methods
> pylint fix code style messages

- src/readToEarn.py
Not sure why these lines were removed! Fixes #291
This was a pain to diagnose, because it is so weird that two very important lines would just be removed. Looks like @Kyrela made some other unneeded cosmetic changes, which thankfully did not cause additional issues.
I'd like to review PRs to this file in the future, especially since it obviously was not tested before committing
> Fixed readToEarn.py

- .github/dependabot.yml
> Set target branch to develop in dependabot configuration

- src/login.py
Based on [this](https://github.com/klept0/MS-Rewards-Farmer/issues/312#issuecomment-2868241423) solution, I implemented support for both the old and the new login form
> updated login.py to work with new login form
