klept0/MS-Rewards-Farmer

main.py
src/browser.py

Have made some changes.
- I removed the driver.close() in the closeBrowser function because this was causing the endless warnings at the end. driver.quit() fully closes and quits the webdriver. the close() closes the active tab so when both are invoked the tab get's closed and browser also. when now the quit() also get's invoked then comes the warning because nothing is open 😄 
- there was a problem with the new goal stuff, wenn there was 1 mobile search left it crashes... so I now have moved the mobileBrowser stuff out of the runtime of the desktopBrowser and "doubled" the goal stuff. (maybe also some preps to flag only desktop only mobile runs)
- changes some of the new print lines regarding the csv stuff to get logged like the other stuff
maybe you can have a look over this changes and …

Warning goal fixes

---

main.py
src/notifier.py

I have added a notification in case of an error in the bot execution.
So when you run it without the verbose notify flag that you get a message in case of an error.
Also I have moved the "header" of the notifications into the send() function of the notifier so there is no doubled stuff.
Hope you like the change.
please double check 😄

moved notifier "header", added error notification

---

README.md
main.py
src/browser.py

Since I have problems with early closed tabs in Chrome version 119 I have added the abbility to select a specific Chrome version as an argument.
So we can execute the script with an older/fixed version of Chrome.
If no argument is passed, then the most recent version of Chromedriver is used

added argument "chromeversion"

---

main.py
src/login.py
src/utils.py

Accounts may need to be verified by SMS or by email after a certain amount of time, will exit account when detected.
Accounts may be locked due to suspicious activity (can be unlocked by SMS verification), will exit account when detected.

added check for verify/locked accounts

---

src/utils.py

Desktop searches for Level 1 is now 50 points for US, unsure about other regions.

pcSearch array contains only 1 object if account is Level 1.

---

src/login.py

-Added support for `https://rewards.bing.com/` hostname to prevent stalling in `execute_login` function. 
-Replaced subsequent `self.utils.waitUntilVisible` call with `time.sleep(10)` to prevent timeout error when visiting new hostname.
-Changes should fix stalling on 'Writing password...' stage.

Fix stalling on 'Writing password...'

---

main.py

If the user hasn't edited `accounts.json` and tries to run the bot without entering their email and password, the bot will log an error and exit.

Fixed Wrong Email Address

---

src/login.py
src/utils.py

This PR attempts to fix the "Stay signed in?" dialog which can occur when logging in.
Of note, this adds `#acceptButton` to the list of items that `tryDismissAllMessages` triggers. This could cause issues however I'm unsure.
Also, it seems that when the accept button is pressed, we are routed to the rewards page itself instead of the account page. Due to this, I've added a check which moves us over to account.microsoft.com. This could be implemented better however works just fine as is and could act as extra assurance that we've logged in.

Handle "Stay signed in?" window

---

src/searches.py

hello, I use this function when searches take too long to refresh the page, and unlock the timer.

Update searches.py to refresh when blocked 

---

requirements.txt

Resolves error cause by version 1.8.0 or newer as _saferef was deleted for that release. I don't know enough about any of these codebases but forcing the use of 1.7.0 should stop it from not working for now

Resolves #95

---

main.py
src/utils.py

To reproduce the bug, raise an exception somewhere in [this block](https://github.com/klept0/MS-Rewards-Farmer/blob/198d6add1002be16ddd0571804093123392e8bf9/main.py#L42-L55). Notice that the call fails because `send_notification` can't be accessed statically.
This PR makes it so the method can be accessed statically, fixing the bug.

Fix bug when sending notification

---

README.md
main.py
requirements.txt
src/__init__.py
src/readToEarn.py

Implemented the mobile app only "Read to Earn" points. Confirmed working 😊
It would be better to cache the token, to avoid getting it every run. That would require extra error checking. Currently "reads" an article and stops if does not increase points. Might want to check points available for the offer, but the request to check status is more bandwidth then reading an article. To be more efficient, current implementation requires knowing the starting point balance, so going first enables that too.
Issue: ReadToEarn function must be called before DailySet, PunchCards,  MorePromotions. I am missing something to allow it to run after them. I get a `[ERROR] JavascriptException: Message: javascript error: dashboard is not defined` if run it after. 
Request: I would like a switch to load/save …

Added "Read to Earn" Capability

---

main.py

Added command line option for user to do searches only with desktop browser or mobile browser. Default behavior without setting the command line option is running both. I removed the random pauses before and after sleep because I think it is redundant when we already have delays set in the Searches class but please do let me know if it vital for avoiding suspicions. I also moved the step for reading articles into mobile searches to split up the tasks a bit. I'll mark this as a draft for now since I'm still testing and want to touch up logging a bit but please do leave suggestions and feedback :smiley: 
Edit: Now updated to be more in line with the existing code in the `develop` branch. Please disregard some of the statements above.

Add command line option to do either mobile or desktop search only

---

src/readToEarn.py

By default the country is always US and if you are not there will set you on a permanent trip.
Used the solution proposed here https://github.com/klept0/MS-Rewards-Farmer/issues/141 by @weltonbraga

fixed Read to Earn country

---

CHANGELOG.md
README.md
accounts.json.sample
requirements.txt
src/account.py
src/browser.py
src/login.py

Pull request to add support of (almost) all methods of signing into a Microsoft account.
Specifically support for the following methods has been added:
- **Passwordless login**, for which the user only enters their email, then is prompted to enter a specific code on their phone. This is supported in both visible and headless mode by displaying the code that the user has to select on their phone in the console window.
- **2FA login with TOTPs**, for which is user has to enter a one-time password in addition to their login details. The user may now store their TOTP key in `accounts.json`, which will then automatically generate the one-time password and submit it, working in both visible and headless mode. If the key is not provided, as fallback the user may still manually put in the OTP. …

Add support for automatic handling of logins with 2FA and for passwordless setups

---

src/activities.py
src/dailySet.py

some cross on its way to pop gets accepted and never comes back (very sad story)
idk if its added already or not, i was told to create something
if its to late - delete it.
-goodluck

Pork shoulders

---

config.yaml
src/login.py
src/utils.py

Send an Apprise notification when receiving a code to validate with Microsoft Authentificator.
This allows users to run the bot in the background, even if they aren't connected/their session expires.
Also convenient if you're not paying attention to the terminal and have phone notifications muted.
Example:

Add apprise notification on login with phone code

---

src/browser.py
src/utils.py

This PR fixes a bug introduced in #248:
Because the default config included a language and country for the browser, the function [getLanguageCountry](https://github.com/klept0/MS-Rewards-Farmer/blob/1671870923e3c5b5a58cadc862eacd8929bbadcf/src/browser.py#L220) was completely useless and always returned the configuration settings.
This sets the default country and language to `None`, so this function can work as expected.

fix (browser): detect default language

---

requirements.txt
src/browser.py

Fixed a problem where the `pycountry` library didn't recognise the country/language code, and trying to get the `alpha_2` attribute caused an error, preventing the whome script from running.
I removed the use of `pycountry` altogether, as the language and country were obtained by searching the locale with `alpha_2`, then getting the `alpha_2` attribute - which seems completely useless, and could only cause problems from what I saw. I don't know if I'm right.
Asking for Cal's review, since he's the one who wrote the `getLanguageCountry` function in the first place.

getLanguageCountry: fix AttributeError, removed dependency

---

.github/ISSUE_TEMPLATE/bug_report.yml
main.py

This should make troubleshooting easier.
- Always log in the log file at the `DEBUG` level, ignoring the user's configuration (which now only applies to the terminal)
- Renamed log files from `activity.log.date` to `activity-date.log`
- Updated the bug report form to encourage users to submit their entire log file, providing more context and making it easier to fix bugs.

Always log DEBUG level messages in the log file

---

.github/ISSUE_TEMPLATE/bug_report.yml
README.md
requirements.txt
src/utils.py

This should make troubleshooting easier.
Adds a `--reset` parameter than, when used:
- Recursively deletes the `sessions` folder
- Deletes the files `google_trends.bak`, `google_trends.dat`, `google_trends.dir` `logs/previous_points_data.json`
- Kills all running chrome instances
- Exits 0

add reset functionality to delete session files and kill chrome processes

---

src/searches.py

Fix #280
The bot was using the config-based geolocation to get google trends instead of the determined-one (which uses the config-one if provided and determines it as a fallback).
The config-based one could be None if not provided, causing this error.

Fix google trends

---

src/activities.py

Some activities, in specific languages, contains nbsps (non-breakable spaces).
This prevents `completeActivity` to work normally, as `f'//*[contains(text(), "{activityTitle}")]'` is used to click on the card, and `activityTitle` corresponds to `activity['title'].replace("\u200b", "").replace("\xa0", " ")` (`\xa0`, the character representing a nbsp, is changed to a normal space), which causes the element search to return no results, raising a `TimeoutException`. This also mean that activities containing a zero-width space (`\u200b`) in their name are subject to the same bug.
This bug can easily be fixed by using `f'//*[contains(text(), "{activity["title"]}")]'` instead to search the card.
- Use the non-formatted activity title in the activity XPATH search

Fix activities that contains non-breakable spaces in their name

---

src/utils.py

Fix #289
This PR refactors `tryDismissAllMessages` to simplify it and ensure a proper error handling.
---
Creating this as a draft PR for now, as I need @cal4's opinion on something:
As shown in #289, the `dashboardPopUpPopUpSelectButton` button doesn't seem to be clickable anymore.
```
2025-05-02 21:54:07,717 [DEBUG] [DISMISS] Dismissing an element by clicking on <a class="dashboardPopUpPopUpSelectButton ng-binding" ng-click="$ctrl.hidePopUpAndApplyFunction($event)" data-bi-id="rx-nav-popup" target="_self" id="reward_pivot_earn">
</a>
Traceback (most recent call last):
File "c:\Tools\MS-Rewards-Farmer\klept0\fix-cookie-banner\src\activities.py", line 163, in completeActivity
self.browser.utils.click(activityElement)
~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
File …
```

Refactor tryDismissAllMessages
